Repository metastable-labs/supermigrate-interface, pull requests merged in 2024-05, with the labels that each got.

#9 Rebuild of Landing Page with Enhanced Animations and Redesign
  .gitignore
  app/[lang]/globals.css
  app/[lang]/index.tsx
  app/[lang]/layout.tsx
  components/faq/index.tsx
  components/faq/types.ts
  components/ham/index.tsx
  components/ham/types.ts
  components/index.ts
  components/navigation/index.tsx
  components/navigation/right.tsx
  components/table/empty.tsx
  components/testimonial/index.tsx
  components/testimonial/types.ts
  hooks/useScreenDetect.tsx
  next.config.mjs
  package.json
  public/icons/close-icon.svg
  public/icons/hero-base-bland-icon.tsx
  public/icons/hero-base-icon.tsx
  public/icons/hero-bg-lines.tsx
  public/icons/hero-fade-shape.tsx
  public/icons/hero-icon.tsx
  public/icons/hero-mode-icon.tsx
  public/icons/hero-optimism-icon.tsx
  public/icons/hero-scroll-icon.tsx
  public/icons/hero-tiles.tsx
  public/icons/index.ts
  public/icons/link-right-arrow.svg
  public/icons/link-right-arrow.tsx
  public/icons/migrator (1).svg
  public/icons/migrator.svg
  public/icons/minus-icon.tsx
  public/icons/super-migrate-logo.tsx
  public/images/earn.svg
  public/images/easy.svg
  public/images/fast.svg
  tailwind.config.ts
  utils/helpers.ts
  views/home/header/action.tsx
  views/home/header/index.tsx
  views/home/header/menu.tsx
  views/home/header/type.ts
  views/home/hero/button.tsx
  views/home/hero/index.tsx
  views/home/index.tsx
  views/home/nav/index.tsx
  views/home/sections/SectionFour.tsx
  views/home/sections/SectionOne.tsx
  views/home/sections/SectionThree.tsx
  views/home/sections/SectionTwo.tsx
  views/home/sections/faqs/dummy.ts
  views/home/sections/faqs/index.tsx
  views/home/sections/footer/dummy.ts
  views/home/sections/footer/index.tsx
  views/home/sections/testimonials/dummy.ts
  views/home/sections/testimonials/index.tsx
  views/new-migrate/migration-steps/step-1/token-info.tsx
  views/new-migrate/migration-steps/step-3/load-step.tsx
  yarn.lock
Labels: enhancement

#16 Landing Page Rebuild
  components/faq/index.tsx
  components/modal/index.tsx
  components/modal/types.ts
  components/navigation/nav-action.tsx
  components/select/index.tsx
  components/select/types.ts
  components/table/empty.tsx
  components/table/index.tsx
  components/table/types.ts
  components/testimonial/index.tsx
  package.json
  public/icons/footer-logo.svg
  public/icons/index.ts
  public/icons/liquidity-link-icon.svg
  public/icons/liquidity-link-icon.tsx
  public/icons/logo-alt.svg
  public/icons/search-icon.svg
  public/icons/success-icon.tsx
  public/icons/telegram-icon.tsx
  public/icons/tiles.tsx
  tailwind.config.ts
  views/home/header/action.tsx
  views/home/header/index.tsx
  views/home/header/menu.tsx
  views/home/header/type.ts
  views/home/hero/button.tsx
  views/home/hero/index.tsx
  views/home/index.tsx
  views/home/sections/SectionFour.tsx
  views/home/sections/SectionOne.tsx
  views/home/sections/SectionThree.tsx
  views/home/sections/SectionTwo.tsx
  views/home/sections/faqs/index.tsx
  views/home/sections/footer/index.tsx
  views/home/sections/testimonials/index.tsx
  views/home/sections/testimonials/types.ts
  views/liquidity/add.tsx
  views/liquidity/dummy.tsx
  views/liquidity/index.tsx
  views/liquidity/info.tsx
  views/liquidity/input.tsx
  views/liquidity/types.ts
Labels: enhancement

#19 Feat: Add font
  app/[lang]/globals.css
  app/[lang]/layout.tsx
  fonts/Biform/biform_regular.otf
  tailwind.config.ts
Labels: enhancement

#20 Dictionary Integration (WIP)
  application/locale/index.ts
  application/locale/types.ts
  dictionaries/de.json
  dictionaries/en.json
  tailwind.config.ts
  views/home/header/action.tsx
  views/home/header/index.tsx
  views/home/header/menu.tsx
  views/home/hero/button.tsx
  views/home/hero/index.tsx
  views/home/sections/SectionOne.tsx
  views/home/sections/SectionTwo.tsx
  views/home/sections/faqs/index.tsx
  views/home/sections/footer/index.tsx
  views/home/sections/testimonials/index.tsx
Labels: enhancement

#30 Dashboard Review Refactor
  components/card/index.tsx
  components/navigation/modal/network.tsx
  components/navigation/nav-link.tsx
  components/table/index.tsx
  components/tiles/index.tsx
  components/welcome/index.tsx
  views/migrate/index.tsx
  views/network-migrate/connect/index.tsx
  views/new-migrate/header.tsx
  views/new-migrate/index.tsx
  views/token-detail/index.tsx
Labels: enhancement

#32 Cleanup: Clean up migration integration
  application/migration/actions.tsx
  application/migration/index.ts
  components/table/index.tsx
  components/table/types.ts
  config/rainbow/config.tsx
  views/network-migrate/index.tsx
  views/new-migrate/migration-steps/step-4/left.tsx
  views/token-detail/contract.tsx
  views/token-detail/index.tsx
  views/token-detail/pull-request.tsx
Labels: bug

#33 Rearrange Routing, Fix Bugs, Update UI, and Improve Translations
  app/[lang]/[network]/app.tsx
  app/[lang]/[network]/bridge/page.tsx
  app/[lang]/[network]/layout.tsx
  app/[lang]/[network]/liquidity/page.tsx
  app/[lang]/[network]/migrate/[tokenId]/page.tsx
  app/[lang]/[network]/migrate/new/page.tsx
  app/[lang]/[network]/migrate/page.tsx
  app/[lang]/dashboard/page.tsx
  app/[lang]/layout.tsx
  app/[lang]/migrate/page.tsx
  app/layout.tsx
  components/announcement/index.tsx
  components/announcement/types.ts
  components/bottomComment/index.tsx
  components/card/index.tsx
  components/index.ts
  components/navigation/index.tsx
  components/navigation/left.tsx
  components/navigation/modal/network.tsx
  components/navigation/modal/wallet.tsx
  components/navigation/nav-action.tsx
  components/navigation/nav-link.tsx
  components/table/empty.tsx
  components/table/index.tsx
  components/tiles/index.tsx
  components/welcome/index.tsx
  dictionaries/de.json
  public/icons/git-close-icon.svg
  public/icons/index.ts
  views/dashboard/index.tsx
  views/dashboard/selection.tsx
  views/dashboard/types.ts
  views/home/header/action.tsx
  views/home/hero/index.tsx
  views/home/index.tsx
  views/index.ts
  views/network-migrate/index.tsx
  views/new-migrate/header.tsx
  views/new-migrate/migration-steps/index.tsx
  views/new-migrate/migration-steps/step-4/index.tsx
  views/new-migrate/migration-steps/step-4/left.tsx
  views/token-detail/contract.tsx
  views/token-detail/pull-request.tsx
Labels: bug, enhancement

#34 Feat: Add bridging & ui fixes
  application/migration/actions.tsx
  application/migration/api.ts
  application/migration/index.ts
  components/button/index.tsx
  components/button/types.ts
  components/loader/index.tsx
  components/loader/types.ts
  public/icons/loading-icon.tsx
  views/token-detail/index.tsx
Labels: enhancement

#40 feat: localisation integration
  application/locale/types.ts
  components/card/index.tsx
  components/file-input/index.tsx
  components/file-sample/index.tsx
  components/input/index.tsx
  components/navigation/index.tsx
  components/navigation/nav-link.tsx
  components/table/address.tsx
  components/table/cta.tsx
  components/table/empty.tsx
  components/table/index.tsx
  components/table/status.tsx
  components/table/types.ts
  components/welcome/index.tsx
  dictionaries/de.json
  dictionaries/en.json
  views/dashboard/index.tsx
  views/dashboard/selection.tsx
  views/liquidity/index.tsx
  views/network-migrate/connect/index.tsx
  views/network-migrate/index.tsx
  views/new-migrate/header.tsx
  views/new-migrate/index.tsx
  views/new-migrate/migration-steps/header.tsx
  views/new-migrate/migration-steps/index.tsx
  views/new-migrate/migration-steps/step-1/index.tsx
  views/new-migrate/migration-steps/step-1/override-section.tsx
  views/new-migrate/migration-steps/step-1/token-info.tsx
  views/new-migrate/migration-steps/step-2/index.tsx
  views/new-migrate/migration-steps/step-3/index.tsx
  views/new-migrate/migration-steps/step-4/index.tsx
  views/new-migrate/migration-steps/step-4/left.tsx
  views/new-migrate/migration-steps/step-4/right.tsx
  views/token-detail/contract.tsx
  views/token-detail/fast-link.tsx
  views/token-detail/hash.tsx
  views/token-detail/index.tsx
  views/token-detail/pull-request.tsx
Labels: enhancement

#43 fix: correct validation for new migration
  views/new-migrate/migration-steps/index.tsx
Labels: bug

#44 feat: Update File Sample
  components/file-input/index.tsx
  components/file-input/types.ts
  components/file-sample/index.tsx
  public/icons/index.ts
  public/icons/svg-icon.svg
  tailwind.config.ts
  views/new-migrate/migration-steps/header.tsx
  views/new-migrate/migration-steps/step-1/token-info.tsx
  views/new-migrate/migration-steps/step-2/index.tsx
Labels: enhancement

#45 feat: Build New Earn Page
  app/[lang]/[network]/earn/page.tsx
  application/locale/types.ts
  components/button/index.tsx
  components/button/types.ts
  components/navigation/index.tsx
  components/navigation/modal/wallet.tsx
  components/navigation/nav-action.tsx
  components/table/address.tsx
  components/table/index.tsx
  components/table/types.ts
  dictionaries/de.json
  dictionaries/en.json
  dictionaries/es.json
  dictionaries/fr.json
  hooks/useTruncateText.ts
  public/icons/barcode-icon.tsx
  public/icons/btc-icon.svg
  public/icons/copy-icon.svg
  public/icons/copy-icon.tsx
  public/icons/earn-announcement.tsx
  public/icons/earn-link-icon.tsx
  public/icons/earn-welcome.tsx
  public/icons/flash-icon.tsx
  public/icons/index.ts
  public/icons/mobile-wallet-icon.svg
  public/icons/pokt-icon.svg
  public/icons/softdao-icon.svg
  public/icons/tokenomy-icon.svg
  public/icons/wallet-alt-icon.tsx
  public/icons/warning-icon.svg
  tailwind.config.ts
  views/earn/index.tsx
  views/earn/primary/action.tsx
  views/earn/primary/index.tsx
  views/earn/primary/types.ts
  views/earn/secondary/action.tsx
  views/earn/secondary/dummy.tsx
  views/earn/secondary/index.tsx
  views/earn/secondary/types.ts
  views/index.ts
  views/new-migrate/migration-steps/step-4/left.tsx
Labels: enhancement

#46 chore: Update Earn Page
  public/icons/earn-welcome.tsx
  public/icons/index.ts
  public/icons/mobile-earn-welcome.svg
  public/icons/mobile-footer-logo.svg
  views/earn/index.tsx
  views/earn/secondary/action.tsx
  views/earn/secondary/dummy.tsx
  views/earn/secondary/index.tsx
  views/earn/secondary/types.ts
  views/home/sections/footer/index.tsx
Labels: enhancement
